

spring:
  application:
    name: userserver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

---
spring:
  profiles: peer1
server:
  port: 8081

---
spring:
  profiles: peer2
server:
  port: 8082
